export const CHANGE_MAINDATA = 'CHANGE_MAINDATA';
export const SET_INDEX = 'SET_INDEX';
export const SET_SELECTED_GOODS = 'SET_SELECTED_GOODS';
export const SET_TOTAL_ACCOUNT = 'SET_TOTAL_ACCOUNT';
export const SET_COMPRESSED_DATA = 'SET_COMPRESSED_DATA';