export const CHANGE_MAINDATA = 'CHANGE_MAINDATA';
export const SET_INDEX = 'SET_INDEX';
export const SET_SELECTED_GOODS = 'SET_SELECTED_GOODS';
export const SET_TOTAL_ACCOUNT = 'SET_TOTAL_ACCOUNT';
export const SET_ISSELECTED = 'SET_ISSELECTED';
export const SET_TOTAL_NUM = 'SET_TOTAL_NUM';